services:
  config.source.chain:
    class: Vainyl\Config\Chain\ConfigSourceChain
  config.factory:
    class: Vainyl\Config\Factory\ConfigFactory
    arguments: ['@storage.prototype']
  config.storage:
    class: Vainyl\Config\Storage\ConfigStorage
    arguments: ['@storage.prototype', '@config.source.chain', '@config.factory']