services:
  config.source.chain:
    class: Vainyl\Config\Chain\ConfigSourceChain
  config.source: '@config.source.chain'
  config.factory:
    class: Vainyl\Config\Factory\ConfigFactory
  config.storage:
    class: Vainyl\Config\Storage\ConfigStorage
    arguments: ['@storage.prototype', '@config.source.chain', '@config.factory']