services:
  config.source.chain:
    class: Vainyl\Config\Chain\ConfigSourceChain
  config.source: '@config.source.chain'
  config.source.yaml:
    class: Vainyl\Config\Source\YamlConfigSource
    tags:
      - {name: 'config.source', priority: 100}
  config.factory:
    class: Vainyl\Config\Factory\ConfigFactory
    arguments: ['@map.prototype']
  config.storage:
    class: Vainyl\Config\Storage\ConfigStorage
    arguments: ['@map.prototype', '@config.source', '@config.factory']