services:
  config.base.chain:
    class: Vainyl\Config\Chain\ConfigBaseChain
    arguments: ['@priority.queue.prototype', '@vector.prototype', '@priority.queue.prototype', '@vector.prototype']
  config.source: '@config.base.chain'
  config.sink: '@config.base.chain'
  config.base.yaml:
    class: Vainyl\Config\Base\YamlConfigBase
    tags:
      - {name: 'config.source', priority: 100}
  config.base.php:
    class: Vainyl\Config\Base\PhpConfigBase
    tags:
      - {name: 'config.source', priority: 200}
      - {name: 'config.sink', priority: 100}
  config.factory:
    class: Vainyl\Config\Factory\ConfigFactory
    arguments: ['@map.prototype']
  config.storage:
    class: Vainyl\Config\Storage\ConfigStorage
    arguments: ['@map.prototype', '@config.source', '@config.factory']